"use server"

import JSZip from "jszip"

export async function deployAgent(agentId: string, nodes: any[], edges: any[]) {
    try {
        console.log(`\n[0rca-Deployer] Start: ${agentId}`)

        // 1. Generate agent.py
        const agentCode = generateAgentCode(agentId, nodes, edges)
        console.log(`[0rca-Deployer] Generated agent.py (${agentCode.length} chars):`)
        console.log("------------------------------------------")
        console.log(agentCode)
        console.log("------------------------------------------")

        // 2. Create Zip
        const zip = new JSZip()
        zip.file("agent.py", agentCode)

        const requirements = `orca-network-sdk\npython-dotenv\n`
        zip.file("requirements.txt", requirements)
        zip.file(".env", "# Generated by 0rca-flow\n")
        zip.file("Procfile", "web: python agent.py\n")

        const zipBlob = await zip.generateAsync({ type: "uint8array" })
        console.log(`[0rca-Deployer] Zip bundle created: ${(zipBlob.length / 1024).toFixed(2)} KB`)

        // 3. Prepare Deployment
        const DEPLOYER_URL = "https://deploy.0rca.live/deploy"
        const DEPLOYER_TOKEN = process.env.DEPLOYER_SERVICE_TOKEN || "orca_test_token_12345"

        const formData = new FormData()
        const file = new Blob([zipBlob as any], { type: 'application/zip' })
        formData.append('file', file, 'agent.zip')
        formData.append('agentId', agentId)

        const envVars = extractEnvVars(nodes)
        formData.append('envVars', JSON.stringify(envVars))

        console.log(`[0rca-Deployer] Protocol: POST ${DEPLOYER_URL}`)
        console.log(`[0rca-Deployer] Payload: ${envVars.length} Environment Variables`)
        envVars.forEach(v => {
            const masked = v.value ? (v.value.slice(0, 6) + "..." + v.value.slice(-4)) : "empty"
            console.log(`   - ${v.key}: ${masked}`)
        })

        const response = await fetch(DEPLOYER_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${DEPLOYER_TOKEN}`
            },
            body: formData
        })

        console.log(`[0rca-Deployer] Response Status: ${response.status} ${response.statusText}`)

        if (!response.ok) {
            const errorText = await response.text()
            console.error(`[0rca-Deployer] Error Body:`, errorText)
            throw new Error(`Deployer error: ${errorText}`)
        }

        const result = await response.json()
        console.log(`[0rca-Deployer] Success:`, result)
        return { success: true, ...result }

    } catch (error: any) {
        console.error("[0rca-Deployer] Critical Failure:", error.message)
        return { success: false, error: error.message }
    }
}

function generateAgentCode(agentId: string, nodes: any[], edges: any[]) {
    const coreNode = nodes.find(n => n.type === 'agentCore')
    const modelNode = nodes.find(n => n.type === 'intelligenceModel')
    const walletNode = nodes.find(n => n.type === 'wallet')
    const mcpNodes = nodes.filter(n => n.type === 'mcpServer')
    const systemPromptNode = nodes.find(n => n.type === 'systemPrompt')

    const name = coreNode?.data?.name || agentId
    const model = modelNode?.data?.model || "gemini/gemini-2.0-flash"
    const systemPrompt = systemPromptNode?.data?.content || "You are a helpful AI assistant."
    const vaultAddress = walletNode?.data?.address || ""

    let code = `import os
import sys
from dotenv import load_dotenv
from orca_agent_sdk.agent import OrcaAgent

# Load environment variables
load_dotenv()

def main():
    # Configuration from environment
    api_key = os.getenv("GOOGLE_API_KEY")
    if not api_key:
        api_key = os.getenv("GEMINI_API_KEY")
    
    # Initialize tools list (MCP Gateways)
    tools = []\n`

    mcpNodes.forEach(node => {
        if (node.data.url) {
            code += `    tools.append({"name": "${node.data.name || 'mcp_gateway'}", "url": "${node.data.url}"})\n`
        }
    })

    code += `
    # Initialize the Sovereign Agent
    agent = OrcaAgent(
        name="${name}",
        model="${model}",
        system_prompt="""${systemPrompt}""",
        price="0.1",
        vault_address="${vaultAddress}",
        api_key=api_key,
        tools=tools
    )

    print(f"[{agent.name}] Initialized with {len(tools)} tools.")
    print(f"[{agent.name}] Local Identity: {agent.vault_address}")
    
    # Start the Server
    # 0rca-deployer expects port 8080 or port from env
    port = int(os.getenv("PORT", 8080))
    agent.run(host="0.0.0.0", port=port)

if __name__ == "__main__":
    main()
`
    return code
}

function extractEnvVars(nodes: any[]) {
    const vars: any[] = []

    // Add essential keys if they exist in nodes
    nodes.forEach(node => {
        if (node.type === 'intelligenceModel' && node.data.apiKey) {
            vars.push({ key: 'GOOGLE_API_KEY', value: node.data.apiKey })
            vars.push({ key: 'GEMINI_API_KEY', value: node.data.apiKey })
        }
        if (node.type === 'wallet' && node.data.privateKey) {
            vars.push({ key: 'AGENT_PRIVATE_KEY', value: node.data.privateKey })
        }
    })

    // Add default 0rca envs
    vars.push({ key: 'ORCA_NETWORK', value: 'mainnet' })

    return vars
}
